// WHEN UPDATE MAKE SURE WHENEVER YOU FAVORITE PHOTO (YOU FAVORITE RIGHT ONE).
// ADD MODAL FOR PROVIDING NAME.
// ADD THUMBNAIL
// HEART ANIMATION WHEN ADDING TO FAVORITE
// CHANGE SKELETON
// SLIDER VIDEO STOP WHEN GO TO NEXT MEDIA
// MEMO THE MEDIA
