// RESIZE PHOTOS IN IMG UPLOAD MODAL
// WRONG PARTICIPANTS NUMBER FIX (AFTER UPLOAD)
// WHEN UPDATE MAKE SURE WHENEVER YOU FAVORITE PHOTO (YOU FAVORITE RIGHT ONE).
// ADD MODAL FOR PROVIDING NAME.
// ADD THUMBNAIL
// HEART ANIMATION WHEN ADDING TO FAVORITE
// CHANGE SKELETON
